#version 460 core
#extension GL_NV_shader_atomic_float : enable
precision highp float;

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

uniform sampler2D referenceImage;
uniform sampler2D currentImage;
uniform int width;

layout(std430, binding = 0) restrict buffer errorValueSSBO {
	float errorValue[];
};


void main(void) {
	float sum = 0.0;
	for(int x = 0; x < width; x++) {
		ivec2 pos = ivec2(x, gl_GlobalInvocationID.x);
		vec3 referenceColor = texelFetch(referenceImage, pos, 0).xyz;
		vec3 currentColor = texelFetch(currentImage, pos, 0).xyz;
		sum += dot(referenceColor - currentColor, referenceColor - currentColor);
	}

	errorValue[gl_GlobalInvocationID.x] = sum;
}