#version 460

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;


layout(std430, binding = 0) restrict buffer DataBuffer {
    uint data[];
};

layout(std430, binding = 1) restrict readonly buffer PartialSums {
    uint partialSums[];
};

void main() 
{
    uint gid = gl_GlobalInvocationID.x;
    uint lid = gl_LocalInvocationID.x;
    uint groupID = gl_WorkGroupID.x;

    if (groupID == 0 || gid >= data.length()) 
        return;

    uint addVal = partialSums[groupID - 1];
    data[gid] += addVal;
}
