#version 460

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;


layout(std430, binding = 1) restrict buffer PartialSums {
    uint partialSums[];
};

shared uint temp[1024];

void main() 
{
    const uint gid = gl_GlobalInvocationID.x;
    const uint lid = gl_LocalInvocationID.x;
    const uint groupSize = gl_WorkGroupSize.x;

    temp[lid] = (gid >= partialSums.length()) ? 0 : partialSums[gid];
    barrier();

    for (uint offset = 1; offset < groupSize; offset <<= 1) 
    {
        uint t = 0;
        if (lid >= offset) 
        {
            t = temp[lid - offset];
        }
        barrier();
        temp[lid] += t;
        barrier();
    }

    if (gid >= partialSums.length())
		return;

    partialSums[gid] = temp[lid];
}
