#version 460

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;


layout(std430, binding = 0) restrict buffer DataBuffer {
    uint data[];
};

layout(std430, binding = 1) restrict writeonly buffer PartialSums {
    uint partialSums[];
};

shared uint temp[1024];

void main() 
{
    const uint gid = gl_GlobalInvocationID.x;
    const uint lid = gl_LocalInvocationID.x;
    const uint groupID = gl_WorkGroupID.x;
    const uint groupSize = gl_WorkGroupSize.x;

    temp[lid] = (gid >= data.length()) ? 0 : data[gid];
    barrier();

    for (uint offset = 1; offset < groupSize; offset <<= 1)
    {
        uint t = 0;
        if (lid >= offset) 
        {
            t = temp[lid - offset];
        }
        barrier();
        temp[lid] += t;
        barrier();
    }

    if (gid >= data.length())
		return;

    data[gid] = temp[lid];

    if (lid == groupSize - 1) 
    {
        partialSums[groupID] = temp[lid];
    }
}
