#include "rectangle.h"

Rectangle::Rectangle(int instanceCount, std::vector<glm::vec3> position, std::vector<glm::vec4> color, std::shared_ptr<renderer::RenderEngine> engine, float a, float b, float c)
	: a(a / 2), b(b / 2), c(c / 2), Geometry(instanceCount, position, color, engine) {
	initGeometry();
}

InputGeometryArray Rectangle::generateGeometry() const {
	InputGeometryArray input;
	input.hasIndexes = false;
	input.renderAs = GL_TRIANGLES;

	input.vertexes.push_back({
		{-a,-b,-c},
		{0,-1,0},
		{0,0}
		});
	input.vertexes.push_back({
		{-a,-b,c},
		{0,-1,0},
		{0,1}
		});
	input.vertexes.push_back({
		{a,-b,c},
		{0,-1,0},
		{1,1}
		});
	input.vertexes.push_back({
		{a,-b,c},
		{0,-1,0},
		{1,1}
		});
	input.vertexes.push_back({
		{a,-b,-c},
		{0,-1,0},
		{1,0}
		});
	input.vertexes.push_back({
		{-a,-b,-c},
		{0,-1,0},
		{0,0}
		});

	input.vertexes.push_back({
		{-a,b,-c},
		{0,1,0},
		{0,0}
		});
	input.vertexes.push_back({
		{-a,b,c},
		{0,1,0},
		{0,1}
		});
	input.vertexes.push_back({
		{a,b,c},
		{0,1,0},
		{1,1}
		});
	input.vertexes.push_back({
		{a,b,c},
		{0,1,0},
		{1,1}
		});
	input.vertexes.push_back({
		{a,b,-c},
		{0,1,0},
		{1,0}
		});
	input.vertexes.push_back({
		{-a,b,-c},
		{0,1,0},
		{0,0}
		});

	input.vertexes.push_back({
		{-a,-b,-c},
		{0,0,-1},
		{1,0}
		});
	input.vertexes.push_back({
		{a,-b,-c},
		{0,0,-1},
		{0,0}
		});
	input.vertexes.push_back({
		{a,b,-c},
		{0,0,-1},
		{0,1}
		});
	input.vertexes.push_back({
		{a,b,-c},
		{0,0,-1},
		{0,1}
		});
	input.vertexes.push_back({
		{-a,b,-c},
		{0,0,-1},
		{1,1}
		});
	input.vertexes.push_back({
		{-a,-b,-c},
		{0,0,-1},
		{1,0}
		});

	input.vertexes.push_back({
		{-a,-b,c},
		{0,0,1},
		{0,0}
		});
	input.vertexes.push_back({
		{a,-b,c},
		{0,0,1},
		{1,0}
		});
	input.vertexes.push_back({
		{a,b,c},
		{0,0,1},
		{1,1}
		});
	input.vertexes.push_back({
		{a,b,c},
		{0,0,1},
		{1,1}
		});
	input.vertexes.push_back({
		{-a,b,c},
		{0,0,1},
		{0,1}
		});
	input.vertexes.push_back({
		{-a,-b,c},
		{0,0,1},
		{0,0}
		});

	input.vertexes.push_back({
		{-a,-b,-c},
		{-1,0,0},
		{0,0}
		});
	input.vertexes.push_back({
		{-a,-b,c},
		{-1,0,0},
		{0,1}
		});
	input.vertexes.push_back({
		{-a,b,c},
		{-1,0,0},
		{1,1}
		});
	input.vertexes.push_back({
		{-a,b,c},
		{-1,0,0},
		{1,1}
		});
	input.vertexes.push_back({
		{-a,b,-c},
		{-1,0,0},
		{1,0}
		});
	input.vertexes.push_back({
		{-a,-b,-c},
		{-1,0,0},
		{0,0}
		});

	input.vertexes.push_back({
		{a,-b,-c},
		{1,0,0},
		{1,0}
		});
	input.vertexes.push_back({
		{a,-b,c},
		{1,0,0},
		{1,1}
		});
	input.vertexes.push_back({
		{a,b,c},
		{1,0,0},
		{0,1}
		});
	input.vertexes.push_back({
		{a,b,c},
		{1,0,0},
		{0,1}
		});
	input.vertexes.push_back({
		{a,b,-c},
		{1,0,0},
		{0,0}
		});
	input.vertexes.push_back({
		{a,-b,-c},
		{1,0,0},
		{1,0}
		});

	return input;
}
