#version 460 compatibility

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

uniform uint pixelCount;

layout(std430, binding = 20) restrict writeonly buffer XCountBuffer {
	uint xCount[];
};
layout(std430, binding = 21) restrict writeonly buffer XOffsetBuffer {
	uint xOffset[];
};
layout(std430, binding = 23) restrict writeonly buffer YRadiusBuffer {
	int yRadius[];
};


void main() {
	uint i = gl_GlobalInvocationID.x;
	if(i >= pixelCount)
		return;

	xCount[i] = 0u;
	xOffset[i] = 0u;
	yRadius[i] = 0;
}
