#version 460 compatibility

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 11) restrict buffer gradientSumSSBO {
	float gradientSum[];
};

layout(std430, binding = 19) restrict readonly buffer gradientSSBO {
	float gradient[];
};


void main() {
	unsigned int index = gl_LocalInvocationID.x + gl_WorkGroupSize.x * gl_WorkGroupID.x;
	if (index >= gradientSum.length()) {
		return;
	}

	gradientSum[index] += gradient[index];
}